### ISSUE TITLE
What is InstanceIsolationRequestHandler used for?

### ISSUE THREAD

**Issue by longweiwork** [sermant-io/Sermant#1426]
### What do you want to ask?

I find that InstanceIsolationRequestHandler extends CircuitBreakerRequestHandler and use CircuitBreakerRequestHandler.onBefore to handle request, so CircuitBreakerRequestHandler will be executed twice, if CircuitBreakerRequestHandler throw CircuitBreakerException, which will be wrapped as InstanceIsolationException.I want to ask why is it designed this way and what is InstanceIsolationRequestHandler used for? Looking forward to the answer, thanks~

**Comment by hanbingleixue** [comment]
The InstanceIsolationRequestHandler is mainly used for instance isolation, which is more focused on client-side calls to the server and restricts calls from upstream. Inheriting CircuitBreakerRequestHandler is because the implementation principle of instance isolation is the same as fusing. When the CircuitBreakerRequestHandler throws a CircuitBreakerException, the InstanceIsolationRequestHandler only wraps the exception, distinguishing between exceptions generated by instance isolation processing rules and exceptions generated by fuse processing rules, and does not cause the CircuitBreakerRequestHandler to execute multiple times.

**Comment by hanbingleixue** [comment]
The question has been answered. No more questions will be raised. Therefore, this issue is closed.
