### ISSUE TITLE
Is it possible to add an 'around' interface to the Interceptor top-level interface. Similar to the @Around annotation in AOP

### ISSUE THREAD

**Issue by Ruanjq98** [sermant-io/Sermant#1489]
### What would you like to be added?

Is it possible to add an around interface to the Interceptor top-level interface. Similar to the @Around annotation in AOP.

Similar to the following:
```java
   @Around("point()")
    public Object test(ProceedingJoinPoint joinPoint) throws Throwable {
         // pre-enhancement
         ............
         
         //Execute pointcut
         Object result = joinPoint.proceed(args);
         // post-enhancement
        .....................
        return result;
```

### Why is this needed?

Because some functions may need to run before and after the entry point. Although you can use Context to pass parameters between contexts, it is cumbersome to use and writing code is not smooth enough.

**Comment by lilai23** [comment]
In our design, we use @Advice.OnMethodEnter and @Advice.OnMethodExit to achieve the @Around effect, which is done by the interface encapsulated by bytebuddy. Another point is that it is common to enhance the same method multiple times or mount multiple Sermants. We also need to manage the execution order of the before method and after method that are enhanced multiple times. So this issue is not suitable for current situation.

**Comment by janyao520** [comment]
Did you solve it  ???

**Comment by Ruanjq98** [comment]
> Did you solve it ???

没有解决，看了下代码不太好改动。目前是用serment提供的上下文接口进行的参数传递。
在before里面
context.setLocalFieldValue("xxx", xxx);
在after
context.getLocalFieldValue("xxx");

**Comment by hanbingleixue** [comment]
Other solutions have been provided. No other questions are replied. Therefore, this issue is closed.
