### ISSUE TITLE
ConfigManager#initialize phase, log warnings/errors, causing agent mount fail

### ISSUE THREAD

**Issue by AYue-94** [sermant-io/Sermant#1591]
### What happened?

i add myList property in config.properties and AgentConfig, and default it is empty string.
```properties
agent.config.myList=
```
when io.sermant.core.config.utils.ConfigValueUtil#parseConfigToCollection, parse empty string, then log warn.
![image](https://github.com/user-attachments/assets/90900659-a0e3-4378-a488-aeefcabd288e)
it cause new LogEventCollector instance created, but Config is not ready, so it cause NPE, and agent mount fail.
![image](https://github.com/user-attachments/assets/831286ac-f1a0-45b5-98a0-28aa36ebcbeb)

### How can we reproduce it (as minimally and precisely as possible)?

you can try set agent.config.serviceInjectList as empty string.

### Sermant version

2.0.0

### OS version

MacOS14.1

**Comment by hanbingleixue** [comment]
@AYue-94 The cause of this problem is that when the configuration type of a configuration item is collection and the configuration content is empty, an warning log is recorded. The LogEventCollector collects and reports warning logs. However, the event configuration is not initialized, so a NullPointerException is thrown on event collection. We will fix it in the next release.
